# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/archos/ac50da/setup-makefiles.sh


#PRODUCT_PACKAGES += \
#    mm-qcamera-daemon \
#    mm-qcamera-app \
#    liboemcamera_32 \
#    libmmcamera2_sensor_modules_32 \
#    libmmcamera2_stats_modules_32  \
#    libmmcamera_ov13850_32 libmmcamera_sunny_q13v04b_eeprom_32 \
#    libmmcamera_ov5670_q5v41b_32 libmmcamera_sunny_q5v41b_eeprom_32 \
#    cpp_firmware_v1_1_1.fw_32 cpp_firmware_v1_1_6.fw_32 cpp_firmware_v1_2_0.fw_32 cpp_firmware_v1_4_0.fw_32

PRODUCT_PACKAGES += \
libactuator_dw9714_q13v04b_32 libmmcamera_sunny_q13v04b_eeprom_32 libmmcamera_sunny_q5v41b_eeprom_32 libmmcamera_ov13850_32 libchromatix_ov13850_preview_32 libchromatix_ov13850_snapshot_32 libchromatix_ov13850_default_video_32 libchromatix_ov13850_hfr_60fps_32 libchromatix_ov13850_hfr_90fps_32 libchromatix_ov13850_hfr_120fps_32 libmmcamera_ov5670_q5v41b_32 libchromatix_ov5670_q5v41b_preview_32 libchromatix_ov5670_q5v41b_snapshot_32 libchromatix_ov5670_q5v41b_default_video_32 libchromatix_ov5670_q5v41b_hfr_60fps_32 libchromatix_ov5670_q5v41b_hfr_90fps_32 libchromatix_ov5670_q5v41b_hfr_120fps_32 libmmcamera2_sensor_modules_32 libmmcamera2_pproc_modules_32 libmmcamera2_isp_modules_32 libmmcamera2_iface_modules_32


PRODUCT_COPY_FILES += \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/archos/ac50da/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/archos/ac50da/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/archos/ac50da/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/archos/ac50da/proprietary/bin/cnd:system/bin/cnd \
    vendor/archos/ac50da/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/archos/ac50da/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/archos/ac50da/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/archos/ac50da/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/archos/ac50da/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/archos/ac50da/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    vendor/archos/ac50da/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/archos/ac50da/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/archos/ac50da/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/archos/ac50da/proprietary/bin/radish:system/bin/radish \
    vendor/archos/ac50da/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/archos/ac50da/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/archos/ac50da/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/archos/ac50da/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    vendor/archos/ac50da/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    vendor/archos/ac50da/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/archos/ac50da/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    vendor/archos/ac50da/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/archos/ac50da/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/archos/ac50da/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/ConnectivityExt.xml:system/etc/permissions/ConnectivityExt.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/archos/ac50da/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/archos/ac50da/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/archos/ac50da/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/archos/ac50da/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/archos/ac50da/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/archos/ac50da/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar \
    vendor/archos/ac50da/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/archos/ac50da/proprietary/lib64/libwcnss_qmi.so:system/lib64/libwcnss_qmi.so \
    vendor/archos/ac50da/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/archos/ac50da/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/archos/ac50da/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libcneconn.so:system/vendor/lib64/libcneconn.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libcneqmiutils.so:system/vendor/lib64/libcneqmiutils.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libcne.so:system/vendor/lib64/libcne.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdataitems.so:system/vendor/lib64/libdataitems.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdpmframework.so:system/vendor/lib64/libdpmframework.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdpmnsrm.so:system/vendor/lib64/libdpmnsrm.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libjni_livedisplay.so:system/vendor/lib64/libjni_livedisplay.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libNimsWrap.so:system/vendor/lib64/libNimsWrap.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libvendorconn.so:system/vendor/lib64/libvendorconn.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so \
    vendor/archos/ac50da/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so \
    vendor/archos/ac50da/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/archos/ac50da/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/archos/ac50da/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    vendor/archos/ac50da/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/archos/ac50da/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/archos/ac50da/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/archos/ac50da/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/archos/ac50da/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/archos/ac50da/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/archos/ac50da/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/archos/ac50da/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_COPY_FILES += \
    vendor/archos/ac50da/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/archos/ac50da/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/archos/ac50da/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/archos/ac50da/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/archos/ac50da/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/archos/ac50da/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \

PRODUCT_COPY_FILES += \
    vendor/archos/ac50da/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \

_PRODUCT_PACKAGES += \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
\
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
\
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/archos/ac50da/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.s \
\
    vendor/archos/ac50da/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api \
    libwpa_qmi_eap_proxy \
    libdiag \
    libdsutils \
    libidl \
    libqmi_cci \
    libqmi_client_qmux \
    libqmi_encdec \
    libqmiservices \
    libtime_genoff \
    libsmemlog \
    shutdownlistener \
    TimeService \
    CNEService \
    com.qualcomm.location \
    dpmserviceapp \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook \
    cktnvtool
endif

